// Generated by CoffeeScript 1.10.0
(function() {
  var vendor, vendorCss;

  vendor = {
    lodash: './bower_components/lodash/lodash.min',
    jq: './bower_components/jquery/dist/jquery.min',
    jqMigrate: './bower_components/jquery-migrate/jquery-migrate',
    ng: './bower_components/angular/angular.min',
    ngSanitize: './bower_components/angular-sanitize/angular-sanitize.min',
    uiRouter: './bower_components/angular-ui-router/release/angular-ui-router.min',
    uiBs: './bower_components/angular-bootstrap/ui-bootstrap-tpls.min',
    webStorage: './bower_components/angular-webstorage/angular-webstorage.min',
    infiniteScroll: './bower_components/ngInfiniteScroll/build/ng-infinite-scroll.min',
    ngLocaleRu: './bower_components/angular-locale-ru/angular-locale_ru',
    ngAnimate: './bower_components/angular-animate/angular-animate.min',
    ngUploader: './bower_components/ng-file-upload/ng-file-upload-all.min',
    notify: './bower_components/remarkable-bootstrap-notify/dist/bootstrap-notify.min',
    yamap: './bower_components/angular-yandex-map/ya-map-2.1.min',
    ngMask: './bower_components/angular-mask/dist/ngMask.min',
    bsTour: './bower_components/bootstrap-tour/build/js/bootstrap-tour.min',
    ngBsTour: './bower_components/angular-bootstrap-tour/dist/angular-bootstrap-tour.min',
    ngLazyImg: './bower_components/angular-lazy-img/release/angular-lazy-img.min'
  };

  vendorCss = {
    bsTour: './bower_components/bootstrap-tour/build/js/bootstrap-tour.min'
  };

}).call(this);

//# sourceMappingURL=require-conf.js.map
